// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sckkxdmwzxayefwvcgic.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNja2t4ZG13enhheWVmd3ZjZ2ljIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI2OTI2MDgsImV4cCI6MjA2ODI2ODYwOH0.bu0p6fXSnlw02qRDkKUCo1IBTwMherhRmJT54NTQd-w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);